CREATE TABLE IF NOT EXISTS utilisateur (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prenom TEXT,
  nom TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  mot_de_passe_hash TEXT NOT NULL,
  telephone TEXT,
  code_postal TEXT,
  supabase_auth_id TEXT,
  date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS supabase_auth_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS utilisateur_email_lower_unique ON utilisateur (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS utilisateur_supabase_auth_id_unique ON utilisateur (supabase_auth_id) WHERE supabase_auth_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS client (
  utilisateur_id INTEGER PRIMARY KEY REFERENCES utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS prestataire (
  utilisateur_id INTEGER PRIMARY KEY REFERENCES utilisateur(id) ON DELETE CASCADE,
  nom_entreprise TEXT,
  description TEXT,
  siret TEXT,
  site_web TEXT,
  adresse_postale TEXT,
  banniere_url TEXT,
  photo_url TEXT
);

CREATE TABLE IF NOT EXISTS favori_prestataire (
  utilisateur_id INTEGER NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
  prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
  date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (utilisateur_id, prestataire_id)
);

CREATE TABLE IF NOT EXISTS type_evenement (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS evenement (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES client(utilisateur_id) ON DELETE CASCADE,
  type_evenement_id INTEGER NOT NULL REFERENCES type_evenement(id),
  titre TEXT NOT NULL,
  description TEXT,
  lieu TEXT,
  date_evenement TEXT,
  date_fin TEXT,
  nombre_invites INTEGER,
  budget DOUBLE PRECISION,
  date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS emplacement_evenement (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evenement_id INTEGER NOT NULL REFERENCES evenement(id) ON DELETE CASCADE,
  libelle TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evenement_prestataire (
  evenement_id INTEGER NOT NULL REFERENCES evenement(id) ON DELETE CASCADE,
  prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
  date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (evenement_id, prestataire_id)
);

CREATE TABLE IF NOT EXISTS zone_intervention (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
  libelle TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS disponibilite (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
  date_debut TEXT NOT NULL,
  date_fin TEXT NOT NULL,
  statut TEXT NOT NULL DEFAULT 'disponible'
);

CREATE TABLE IF NOT EXISTS categorie_prestation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS prestation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
  categorie_id INTEGER NOT NULL REFERENCES categorie_prestation(id),
  titre TEXT NOT NULL,
  description TEXT,
  prix DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS option_prestation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prestation_id INTEGER NOT NULL REFERENCES prestation(id) ON DELETE CASCADE,
  libelle TEXT NOT NULL,
  prix_supplement DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS media_prestation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prestation_id INTEGER NOT NULL REFERENCES prestation(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  type_media TEXT NOT NULL DEFAULT 'image',
  legende TEXT
);

ALTER TABLE utilisateur ENABLE ROW LEVEL SECURITY;
ALTER TABLE client ENABLE ROW LEVEL SECURITY;
ALTER TABLE prestataire ENABLE ROW LEVEL SECURITY;
ALTER TABLE favori_prestataire ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_evenement ENABLE ROW LEVEL SECURITY;
ALTER TABLE evenement ENABLE ROW LEVEL SECURITY;
ALTER TABLE emplacement_evenement ENABLE ROW LEVEL SECURITY;
ALTER TABLE evenement_prestataire ENABLE ROW LEVEL SECURITY;
ALTER TABLE zone_intervention ENABLE ROW LEVEL SECURITY;
ALTER TABLE disponibilite ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorie_prestation ENABLE ROW LEVEL SECURITY;
ALTER TABLE prestation ENABLE ROW LEVEL SECURITY;
ALTER TABLE option_prestation ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_prestation ENABLE ROW LEVEL SECURITY;

INSERT INTO type_evenement (libelle) VALUES
  ('Mariage'), ('Anniversaire'), ('Séminaire'), ('Soirée d’entreprise'), ('Baptême')
ON CONFLICT (libelle) DO NOTHING;

INSERT INTO categorie_prestation (libelle) VALUES
  ('Traiteur'), ('Photographie'), ('Décoration'), ('Musique'), ('Lieu de réception')
ON CONFLICT (libelle) DO NOTHING;