CREATE TABLE IF NOT EXISTS public.prestataire_tache (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestataire_id INTEGER NOT NULL REFERENCES public.prestataire(utilisateur_id) ON DELETE CASCADE,
	titre TEXT NOT NULL CHECK (length(btrim(titre)) BETWEEN 1 AND 160),
	description TEXT,
	date_echeance DATE,
	statut TEXT NOT NULL DEFAULT 'a_faire' CHECK (statut IN ('a_faire', 'en_cours', 'terminee')),
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.conversation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	client_id INTEGER NOT NULL REFERENCES public.client(utilisateur_id) ON DELETE CASCADE,
	prestataire_id INTEGER NOT NULL REFERENCES public.prestataire(utilisateur_id) ON DELETE CASCADE,
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (client_id, prestataire_id)
);

CREATE TABLE IF NOT EXISTS public.message (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	conversation_id INTEGER NOT NULL REFERENCES public.conversation(id) ON DELETE CASCADE,
	expediteur_id INTEGER NOT NULL REFERENCES public.utilisateur(id) ON DELETE CASCADE,
	contenu TEXT NOT NULL CHECK (length(btrim(contenu)) BETWEEN 1 AND 4000),
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lu_le TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS prestataire_tache_owner_status_idx
	ON public.prestataire_tache (prestataire_id, statut, date_echeance);
CREATE INDEX IF NOT EXISTS conversation_provider_idx
	ON public.conversation (prestataire_id, id);
CREATE INDEX IF NOT EXISTS message_conversation_id_idx
	ON public.message (conversation_id, id);

ALTER TABLE public.prestataire_tache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message ENABLE ROW LEVEL SECURITY;