CREATE TABLE IF NOT EXISTS utilisateur (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prenom TEXT,
	nom TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	mot_de_passe_hash TEXT NOT NULL,
	telephone TEXT,
	code_postal TEXT,
	supabase_auth_id TEXT,
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS supabase_auth_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS utilisateur_email_lower_unique ON utilisateur (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS utilisateur_supabase_auth_id_unique ON utilisateur (supabase_auth_id) WHERE supabase_auth_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS client (
	utilisateur_id INTEGER PRIMARY KEY REFERENCES utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS prestataire (
	utilisateur_id INTEGER PRIMARY KEY REFERENCES utilisateur(id) ON DELETE CASCADE,
	nom_entreprise TEXT,
	description TEXT,
	siret TEXT,
	site_web TEXT,
	adresse_postale TEXT,
	banniere_url TEXT,
	photo_url TEXT
);

CREATE TABLE IF NOT EXISTS favori_prestataire (
	utilisateur_id INTEGER NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
	prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (utilisateur_id, prestataire_id)
);

CREATE TABLE IF NOT EXISTS type_evenement (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	libelle TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS evenement (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	client_id INTEGER NOT NULL REFERENCES client(utilisateur_id) ON DELETE CASCADE,
	type_evenement_id INTEGER NOT NULL REFERENCES type_evenement(id),
	titre TEXT NOT NULL,
	description TEXT,
	lieu TEXT,
	date_evenement TEXT,
	date_fin TEXT,
	nombre_invites INTEGER,
	budget DOUBLE PRECISION,
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS emplacement_evenement (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	evenement_id INTEGER NOT NULL REFERENCES evenement(id) ON DELETE CASCADE,
	libelle TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evenement_prestataire (
	evenement_id INTEGER NOT NULL REFERENCES evenement(id) ON DELETE CASCADE,
	prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (evenement_id, prestataire_id)
);

CREATE TABLE IF NOT EXISTS zone_intervention (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
	libelle TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS disponibilite (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
	date_debut TEXT NOT NULL,
	date_fin TEXT NOT NULL,
	statut TEXT NOT NULL DEFAULT 'disponible'
);

CREATE TABLE IF NOT EXISTS categorie_prestation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	libelle TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS prestation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestataire_id INTEGER NOT NULL REFERENCES prestataire(utilisateur_id) ON DELETE CASCADE,
	categorie_id INTEGER NOT NULL REFERENCES categorie_prestation(id),
	titre TEXT NOT NULL,
	description TEXT,
	prix DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS option_prestation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestation_id INTEGER NOT NULL REFERENCES prestation(id) ON DELETE CASCADE,
	libelle TEXT NOT NULL,
	prix_supplement DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS media_prestation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestation_id INTEGER NOT NULL REFERENCES prestation(id) ON DELETE CASCADE,
	url TEXT NOT NULL,
	type_media TEXT NOT NULL DEFAULT 'image',
	legende TEXT
);

ALTER TABLE utilisateur ENABLE ROW LEVEL SECURITY;
ALTER TABLE client ENABLE ROW LEVEL SECURITY;
ALTER TABLE prestataire ENABLE ROW LEVEL SECURITY;
ALTER TABLE favori_prestataire ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_evenement ENABLE ROW LEVEL SECURITY;
ALTER TABLE evenement ENABLE ROW LEVEL SECURITY;
ALTER TABLE emplacement_evenement ENABLE ROW LEVEL SECURITY;
ALTER TABLE evenement_prestataire ENABLE ROW LEVEL SECURITY;
ALTER TABLE zone_intervention ENABLE ROW LEVEL SECURITY;
ALTER TABLE disponibilite ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorie_prestation ENABLE ROW LEVEL SECURITY;
ALTER TABLE prestation ENABLE ROW LEVEL SECURITY;
ALTER TABLE option_prestation ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_prestation ENABLE ROW LEVEL SECURITY;

INSERT INTO type_evenement (libelle) VALUES
	('Mariage'), ('Anniversaire'), ('Séminaire'), ('Soirée d’entreprise'), ('Baptême')
ON CONFLICT (libelle) DO NOTHING;

INSERT INTO categorie_prestation (libelle) VALUES
	('Traiteur'), ('Photographie'), ('Décoration'), ('Musique'), ('Lieu de réception')
ON CONFLICT (libelle) DO NOTHING;

ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS derniere_connexion TIMESTAMPTZ;

ALTER TABLE public.favori_prestataire
	DROP CONSTRAINT IF EXISTS favori_prestataire_utilisateur_id_fkey;

ALTER TABLE public.favori_prestataire
	RENAME COLUMN utilisateur_id TO client_id;

DELETE FROM public.favori_prestataire f
WHERE NOT EXISTS (
	SELECT 1
	FROM public.client c
	WHERE c.utilisateur_id = f.client_id
);

ALTER TABLE public.favori_prestataire
	ADD CONSTRAINT favori_prestataire_client_id_fkey
	FOREIGN KEY (client_id) REFERENCES public.client(utilisateur_id) ON DELETE CASCADE;

ALTER TABLE public.utilisateur
	ADD COLUMN IF NOT EXISTS type_utilisateur TEXT NOT NULL DEFAULT 'client';

UPDATE public.utilisateur u
SET type_utilisateur = CASE
	WHEN EXISTS (SELECT 1 FROM public.client c WHERE c.utilisateur_id = u.id) THEN 'client'
	WHEN EXISTS (SELECT 1 FROM public.prestataire p WHERE p.utilisateur_id = u.id) THEN 'prestataire'
	ELSE 'client'
END;

ALTER TABLE public.utilisateur
	ADD CONSTRAINT utilisateur_type_utilisateur_check
	CHECK (type_utilisateur IN ('client', 'prestataire'));

CREATE TABLE IF NOT EXISTS public.prestataire_tache (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	prestataire_id INTEGER NOT NULL REFERENCES public.prestataire(utilisateur_id) ON DELETE CASCADE,
	titre TEXT NOT NULL CHECK (length(btrim(titre)) BETWEEN 1 AND 160),
	description TEXT,
	date_echeance DATE,
	statut TEXT NOT NULL DEFAULT 'a_faire' CHECK (statut IN ('a_faire', 'en_cours', 'terminee')),
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.conversation (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	client_id INTEGER NOT NULL REFERENCES public.client(utilisateur_id) ON DELETE CASCADE,
	prestataire_id INTEGER NOT NULL REFERENCES public.prestataire(utilisateur_id) ON DELETE CASCADE,
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (client_id, prestataire_id)
);

CREATE TABLE IF NOT EXISTS public.message (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	conversation_id INTEGER NOT NULL REFERENCES public.conversation(id) ON DELETE CASCADE,
	expediteur_id INTEGER NOT NULL REFERENCES public.utilisateur(id) ON DELETE CASCADE,
	contenu TEXT NOT NULL CHECK (length(btrim(contenu)) BETWEEN 1 AND 4000),
	date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lu_le TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS prestataire_tache_owner_status_idx
	ON public.prestataire_tache (prestataire_id, statut, date_echeance);
CREATE INDEX IF NOT EXISTS conversation_provider_idx
	ON public.conversation (prestataire_id, id);
CREATE INDEX IF NOT EXISTS message_conversation_id_idx
	ON public.message (conversation_id, id);

ALTER TABLE public.prestataire_tache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message ENABLE ROW LEVEL SECURITY;

UPDATE public.utilisateur u
SET type_utilisateur = 'prestataire'
WHERE u.type_utilisateur <> 'prestataire'
  AND EXISTS (
    SELECT 1
    FROM public.prestataire p
    WHERE p.utilisateur_id = u.id
  );

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM public.utilisateur
		WHERE telephone IS NOT NULL
		GROUP BY telephone
		HAVING COUNT(*) > 1
	) THEN
		RAISE EXCEPTION 'Impossible de rendre utilisateur.telephone unique : des numéros en double existent.';
	END IF;
END;
$$;

UPDATE public.utilisateur
SET prenom = 'Utilisateur'
WHERE prenom IS NULL OR btrim(prenom) = '';

ALTER TABLE public.utilisateur
	ALTER COLUMN prenom SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS utilisateur_telephone_unique
	ON public.utilisateur (telephone);

ALTER TABLE public.utilisateur ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.type_evenement ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.evenement ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.emplacement_evenement ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.zone_intervention ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.disponibilite ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.categorie_prestation ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.prestation ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.option_prestation ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.media_prestation ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.prestataire_tache ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.conversation ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE public.message ALTER COLUMN id SET GENERATED ALWAYS;
